### ISSUE TITLE
Variable declaration after goto Label

### ISSUE THREAD

**Issue by polluks** [fpjohnston/TECO-64#6]
````
Making env_sys.o
../src/env_sys.c: In function 'teco_env':
../src/env_sys.c:225:13: error: a label can only be part of a statement and a declaration is not a statement
  225 |             pid_t pid = tcgetpgrp(STDIN_FILENO);
      |             ^~~~~
make: *** [Makefile:411: env_sys.o] Error 1
````
https://stackoverflow.com/questions/8384388/variable-declaration-after-goto-label

**Comment by fpjohnston** [comment]
I'm a little confused about the error, but I *think* it's probably
occurring because your compiler won't allow declarations following
*case *statements.
So the remedy would then be to enclose the body of the *case* in braces, as
follows:

        case -5:
        {
            pid_t pid = tcgetpgrp(STDIN_FILENO);

            if (pid == -1)
            {
                return -1;              // Process is child or detached
            }
            else if (pid == getpgrp())
            {
                return (int)pid;        // Foreground process
            }
            else
            {
                return 0;               // Background process
            }
        }

Could you please try this and let me know if it fixes the problem? If so, I
can include the change in the next release.

Thanks.

**Comment by polluks** [comment]
works, thx
