### ISSUE TITLE
New target

### ISSUE THREAD

**Issue by polluks** [fpjohnston/TECO-64#9]
How about an "install" target for the makefile?

**Comment by fpjohnston** [comment]
I don't know how you've been using TECO or how you would like to use it;
could you elaborate, so that I have a better idea what you're trying to
accomplish? And is this just for you, or are there others who would benefit
from such a feature?

**Comment by polluks** [comment]
An install target is pretty common like the clean one.
For example `install -s bin/teco /usr/local/bin`

**Comment by fpjohnston** [comment]
I guess you're not going to answer my questions.

**Comment by polluks** [comment]
My motivation: Use this project without studying the implementation details.
So the term common means I am not speaking for myself alone.
By the way GNU also recommends `make check` for your `make critic`,
see https://stackoverflow.com/questions/1735473/what-does-make-check-do.

**Comment by fpjohnston** [comment]
From the GNU documentation: _make check_ is used to "set up any auxiliary programs or other files needed by the tests". But that's not the purpose of _make critic_, which I created to assist me in running _.perlcritic_ on the Perl scripts I use during the build process. It should never be needed by an end user (which is why it's not displayed when executing the _make help_ target. So I don't think that changing the name would make any sense. The documentation also says that it is typically used after running _configure_, something else I don't provide, along with the _site.exp_ file that _check_ commonly depends on.

I understood that you are not alone in expecting an _install_ target for makefiles generally, but I was asking specifically about TECO. Are there multiple people you are aware of that are using it? And if so, can you tell me why any of you have chosen it over similar available tools? You said something some weeks ago about using it in an Amiga sandbox, but I'd like to know more.

**Comment by fpjohnston** [comment]
This issue has been closed due to lack of any further feedback.

**Comment by fpjohnston** [comment]
I posted a new release that includes an "install" target. This copies an executable image to /usr/local/bin, and also copies the lib/*.tec files to /usr/local/lib/teco.

**Comment by fpjohnston** [comment]
Latest version avoids the use of 'undefine' in makefiles.
